<?
define("STOP_STATISTICS", true);
define("PUBLIC_AJAX_MODE", true);
require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
?>
<div>
	<?$APPLICATION->IncludeComponent(
			"bitrix:news.detail",
			"product-card",
			array(
					"COMPONENT_TEMPLATE" => "product-card",
					"IBLOCK_TYPE" => "products",
					"IBLOCK_ID" => "4",
					"ELEMENT_ID" => $_REQUEST["PRODUCT_ID"],
					"ELEMENT_CODE" => "",
					"CHECK_DATES" => "Y",
					"FIELD_CODE" => array(
							0 => "",
							1 => "",
					),
					"PROPERTY_CODE" => array(
							0 => "LIST_PACKAGE",
							1 => "TYPE",
							2 => "LIST_EVROPODVES",
							3 => "LIST_BLOCK",
							4 => "LIST_CARTON",
							5 => "LIST_PACKING",
							6 => "LIST_MATERIAL",
							7 => "LIST_IMN",
							8 => "LIST_DESCRIPTION",
							9 => "LIST_MANUFACTURER",
							10 => "LIST_CONTRAINDICATIONS",
							11 => "LIST_CERTIFICATE",
							12 => "LIST_PROPERTIES",
							13 => "LIST_USAGE",
							14 => "LIST_SHELFLIFE",
							15 => "LIST_COUNTRY",
							16 => "LIST_STORAGE",
							17 => "HIT",
							18 => "LIST_COLOR",
							19 => "PRICE",
							20 => "PHARMACIES",
							21 => "PHARMACIES_LINKS",
							22 => "",
					),
					"IBLOCK_URL" => "",
					"DETAIL_URL" => "",
					"AJAX_MODE" => "N",
					"AJAX_OPTION_JUMP" => "N",
					"AJAX_OPTION_STYLE" => "Y",
					"AJAX_OPTION_HISTORY" => "N",
					"AJAX_OPTION_ADDITIONAL" => "",
					"CACHE_TYPE" => "N",
					"CACHE_TIME" => "36000000",
					"CACHE_GROUPS" => "N",
					"SET_TITLE" => "N",
					"SET_CANONICAL_URL" => "N",
					"SET_BROWSER_TITLE" => "N",
					"BROWSER_TITLE" => "-",
					"SET_META_KEYWORDS" => "N",
					"META_KEYWORDS" => "-",
					"SET_META_DESCRIPTION" => "N",
					"META_DESCRIPTION" => "-",
					"SET_LAST_MODIFIED" => "N",
					"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
					"ADD_SECTIONS_CHAIN" => "N",
					"ADD_ELEMENT_CHAIN" => "N",
					"ACTIVE_DATE_FORMAT" => "d.m.Y",
					"USE_PERMISSIONS" => "N",
					"STRICT_SECTION_CHECK" => "N",
					"DISPLAY_DATE" => "Y",
					"DISPLAY_NAME" => "Y",
					"DISPLAY_PICTURE" => "Y",
					"DISPLAY_PREVIEW_TEXT" => "Y",
					"USE_SHARE" => "N",
					"PAGER_TEMPLATE" => ".default",
					"DISPLAY_TOP_PAGER" => "N",
					"DISPLAY_BOTTOM_PAGER" => "Y",
					"PAGER_TITLE" => "Страница",
					"PAGER_SHOW_ALL" => "N",
					"PAGER_BASE_LINK_ENABLE" => "N",
					"SET_STATUS_404" => "N",
					"SHOW_404" => "N",
					"MESSAGE_404" => ""
			),
			false
	);?>
</div>
<? require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/epilog_after.php"); ?>